name: Build and Deploy Web Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: dotnet restore ./CalicotEncheres/

      - name: Build the application
        run: dotnet build ./CalicotEncheres/ --configuration Release

      - name: Publish the application
        run: dotnet publish ./CalicotEncheres/ --configuration Release --output ./publish

      - name: Download Web App Publish Profile
        run: |
        PROFILE=$(az webapp deployment list-publishing-profiles --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --name app-calicot-${{ vars.ENVIRONMENT }}-${{ vars.ID_CODE }} --xml)
        echo "$PROFILE" > publish_profile.xml
      
      - name: Upload publish profile as artifact
        uses: actions/upload-artifact@v2
        with:
      
      - name: publish-profile
        path: publish_profile.xml

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-calicot-dev-14   
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}  
          package: ./publish 
     
      - name: Clean up
        run: rm -rf ./publish

