name: Infrastructure Deployment

on:
  workflow_dispatch: 
jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1

    - name: Log in to Azure using Service Principal
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy Infrastructure with Terraform
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Clean up
      run: terraform destroy -auto-approve
      if: failure()  

